# Systemd override to run '/usr/sbin/rndc sync' before a reload or stop of
# bind9. This helps to keep journals and zones in sync, to prevent fatal "out
# of sync" errors.
#
# The empty 'ExecReload' and 'ExecStop' clear the defaults, to make the
# overrides actually possible. Otherwise, the below definitions wouldn't have
# any effect.
[Service]
ExecReload=
ExecReload=/usr/sbin/rndc sync
ExecReload=/usr/sbin/rndc reload

ExecStop=
ExecStop=/usr/sbin/rndc sync
ExecStop=/usr/sbin/rndc stop
