---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: debian13
    box: debian/trixie64
  - name: debian12
    box: debian/bookworm64
provisioner:
  name: ansible
  become: true
lint: yamllint .
